title: Finn Oâ€™Connor
description: Portfolio
theme: null
markdown: kramdown

# IMPORTANT: for project sites (your URL includes /finnoconnorportfolio.github.io)
baseurl: "/finnoconnorportfolio.github.io"
